name: Action di morti
on:
  push: 
jobs: 
  ciao:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "qualcosa"
      - run: echo "ciao jade"
      - run: python --version
      - run: pip --version
      - run: ifconfig
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            morti
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1' 
      - run: python --version
      - run: pip install -r requirements.txt
        working-directory: morti
      - run: python training_ML_morti.py --dataset_path=house_price_regression_dataset.csv
        working-directory: morti