name: Action di morti
on:
  push: 
jobs: 
  ciao:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "qualcosa"
      - run: echo "ciao jade"
      - run: python --version
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
